{{- if .Values.ingress.enabled -}}
{{- $fullName := include "netdata.name" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $apiVersion := (include "netdata.ingress.apiVersion" .) -}}

apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}-rooter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          {{- if not (eq $apiVersion "extensions/v1beta1" "networking.k8s.io/v1beta1") }}
        - pathType: Prefix
          {{- end }}
          path: "{{ $ingressPath }}"
          backend:
            {{- if eq $apiVersion "extensions/v1beta1" "networking.k8s.io/v1beta1" }}
            serviceName: {{ $fullName }}
            servicePort: http
            {{- else }}
            service:
              name: {{ $fullName }}
              port:
                number: 19999
            {{- end }}
  {{- end }}
{{- end }}
