{{- if .Values.serviceAccount.create -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by": "Helm"
  annotations:
    meta.helm.sh/release-name": "netdata"
    meta.helm.sh/release-namespace": "{{ .Release.Namespace }}"
{{- end -}}